version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: root
    - location: scripts/after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 30
      runas: root

  ValidateService:
    - location: scripts/smoke_test.sh
      timeout: 30
      runas: root
